name: Spring Petclinic CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - name: Execute tests with maven wrapper
        run: ./mvnw test
      - name: Build with maven wrapper
        run: ./mvnw package
      - name: Build a Docker image
        run: docker build -t spring-petclinic:latest .
      - name: Login to JFrog Artifactory
        run: echo "${{ secrets.JFROG_API_TOKEN }}" | docker login ${{ secrets.JFROG_URL }}/artifactory/${{ secrets.DOCKER_REPO }} -u${{ secrets.JFROG_USERNAME }} --password-stdin
      - name: Tag Docker image for JFrog
        #run: docker tag spring-petclinic:latest ${{ secrets.JFROG_URL }}/artifactory/${{ secrets.DOCKER_REPO }}/spring-petclinic:latest
        run: docker tag ${{ secrets.JFROG_DOMAIN }}/${{ secrets.DOCKER_REPO }}/spring-petclinic ${{ secrets.JFROG_DOMAIN }}/${{ secrets.DOCKER_REPO }}/spring-petclinic:latest
      - name: Push Docker image to JFrog Artifactory
        #run: docker push ${{ secrets.JFROG_URL }}/artifactory/${{ secrets.DOCKER_REPO }}/spring-petclinic:latest
        run: docker push ${{ secrets.JFROG_DOMAIN }}/${{ secrets.DOCKER_REPO }}/spring-petclinic:latest
